version: "2"

linters:
  enable:
    - kubeapilinter

  settings:
    custom:
      kubeapilinter:
        path: "bin/kube-api-linter.so"
        description: Kube API Linter lints Kube like APIs based on API conventions and best practices.
        original-url: sigs.k8s.io/kube-api-linter
        settings:
          linters: {}
          lintersConfig: {}
