//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

// TODO(MG-331): This is a minimal stub. The boilerplate openapi-gen target
// uses deprecated -i flags that fail with the current openapi-gen binary.
// Once the boilerplate Makefile is fixed, re-run `make generate` to produce
// the real definitions. The stub does not affect CRD validation (which uses
// controller-gen, not openapi-gen).

package v1

import (
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{}
}
