//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatherSpec) DeepCopyInto(out *GatherSpec) {
	*out = *in
	if in.Audit != nil {
		in, out := &in.Audit, &out.Audit
		*out = new(bool)
		**out = **in
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Since != nil {
		in, out := &in.Since, &out.Since
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.SinceTime != nil {
		in, out := &in.SinceTime, &out.SinceTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatherSpec.
func (in *GatherSpec) DeepCopy() *GatherSpec {
	if in == nil {
		return nil
	}
	out := new(GatherSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageStreamTagRef) DeepCopyInto(out *ImageStreamTagRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageStreamTagRef.
func (in *ImageStreamTagRef) DeepCopy() *ImageStreamTagRef {
	if in == nil {
		return nil
	}
	out := new(ImageStreamTagRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MustGather) DeepCopyInto(out *MustGather) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(MustGatherStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MustGather.
func (in *MustGather) DeepCopy() *MustGather {
	if in == nil {
		return nil
	}
	out := new(MustGather)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MustGather) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MustGatherList) DeepCopyInto(out *MustGatherList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MustGather, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MustGatherList.
func (in *MustGatherList) DeepCopy() *MustGatherList {
	if in == nil {
		return nil
	}
	out := new(MustGatherList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MustGatherList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MustGatherSpec) DeepCopyInto(out *MustGatherSpec) {
	*out = *in
	if in.ImageStreamRef != nil {
		in, out := &in.ImageStreamRef, &out.ImageStreamRef
		*out = new(ImageStreamTagRef)
		**out = **in
	}
	if in.GatherSpec != nil {
		in, out := &in.GatherSpec, &out.GatherSpec
		*out = new(GatherSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MustGatherTimeout != nil {
		in, out := &in.MustGatherTimeout, &out.MustGatherTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.UploadTarget != nil {
		in, out := &in.UploadTarget, &out.UploadTarget
		*out = new(UploadTargetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RetainResourcesOnCompletion != nil {
		in, out := &in.RetainResourcesOnCompletion, &out.RetainResourcesOnCompletion
		*out = new(bool)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(Storage)
		(*in).DeepCopyInto(*out)
	}
	if in.Obfuscate != nil {
		in, out := &in.Obfuscate, &out.Obfuscate
		*out = new(ObfuscateConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MustGatherSpec.
func (in *MustGatherSpec) DeepCopy() *MustGatherSpec {
	if in == nil {
		return nil
	}
	out := new(MustGatherSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MustGatherStatus) DeepCopyInto(out *MustGatherStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = (*in).DeepCopy()
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Completed != nil {
		in, out := &in.Completed, &out.Completed
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MustGatherStatus.
func (in *MustGatherStatus) DeepCopy() *MustGatherStatus {
	if in == nil {
		return nil
	}
	out := new(MustGatherStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObfuscateConfig) DeepCopyInto(out *ObfuscateConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ObfuscationConfigRef != nil {
		in, out := &in.ObfuscationConfigRef, &out.ObfuscationConfigRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(PersistentVolumeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObfuscateConfig.
func (in *ObfuscateConfig) DeepCopy() *ObfuscateConfig {
	if in == nil {
		return nil
	}
	out := new(ObfuscateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeClaimReference) DeepCopyInto(out *PersistentVolumeClaimReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeClaimReference.
func (in *PersistentVolumeClaimReference) DeepCopy() *PersistentVolumeClaimReference {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeClaimReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeConfig) DeepCopyInto(out *PersistentVolumeConfig) {
	*out = *in
	out.Claim = in.Claim
	if in.SubPath != nil {
		in, out := &in.SubPath, &out.SubPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeConfig.
func (in *PersistentVolumeConfig) DeepCopy() *PersistentVolumeConfig {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SFTPSpec) DeepCopyInto(out *SFTPSpec) {
	*out = *in
	out.CaseManagementAccountSecretRef = in.CaseManagementAccountSecretRef
	if in.InternalUser != nil {
		in, out := &in.InternalUser, &out.InternalUser
		*out = new(bool)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SFTPSpec.
func (in *SFTPSpec) DeepCopy() *SFTPSpec {
	if in == nil {
		return nil
	}
	out := new(SFTPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Storage) DeepCopyInto(out *Storage) {
	*out = *in
	in.PersistentVolume.DeepCopyInto(&out.PersistentVolume)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Storage.
func (in *Storage) DeepCopy() *Storage {
	if in == nil {
		return nil
	}
	out := new(Storage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadTargetSpec) DeepCopyInto(out *UploadTargetSpec) {
	*out = *in
	if in.SFTP != nil {
		in, out := &in.SFTP, &out.SFTP
		*out = new(SFTPSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadTargetSpec.
func (in *UploadTargetSpec) DeepCopy() *UploadTargetSpec {
	if in == nil {
		return nil
	}
	out := new(UploadTargetSpec)
	in.DeepCopyInto(out)
	return out
}
