apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: must-gather-admin
roleRef:
  kind: ClusterRole
  name: must-gather-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: must-gather-admin
  namespace: support-log-gather
