apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: must-gather-minimal
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/log  # For oc adm node-logs
  - nodes/proxy  # For accessing node metrics
  - pods
  - pods/log  # For pod logs
  - services
  - endpoints
  - persistentvolumes
  - persistentvolumeclaims
  - namespaces
  - configmaps
  - secrets  # Limited to service account tokens
  - events
  - limitranges
  - resourcequotas
  - replicationcontrollers
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups: [""]
  resources:
  - pods/exec
  verbs:
  - create  # Required for oc exec
- apiGroups: [""]
  resources:
  - pods/portforward
  verbs:
  - create  # Required for oc cp
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - list
- apiGroups: ["storage.k8s.io"]
  resources:
  - storageclasses
  - volumeattachments
  - csidrivers
  - csinodes
  - volumesnapshotclasses
  - volumesnapshotcontents
  - csistoragecapacities
  verbs:
  - get
  - list
- apiGroups: ["certificates.k8s.io"]
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
- apiGroups: ["apiregistration.k8s.io"]
  resources:
  - apiservices
  verbs:
  - get
  - list
- apiGroups: ["flowcontrol.apiserver.k8s.io"]
  resources:
  - prioritylevelconfigurations
  - flowschemas
  verbs:
  - get
  - list
- apiGroups: [""]
  resources:
  - projects  # OpenShift namespaces
  verbs:
  - get
  - list
- apiGroups: ["config.openshift.io"]
  resources:
  - clusterversions
  - clusteroperators
  - networks
  - apiservers
  - infrastructures
  - ingresses
  - featuregates
  verbs:
  - get
  - list
- apiGroups: ["operator.openshift.io"]
  resources:
  - networks
  - imagecontentsourcepolicies
  - ingresscontrollers
  verbs:
  - get
  - list
- apiGroups: ["quota.openshift.io"]
  resources:
  - clusterresourcequotas
  verbs:
  - get
  - list
- apiGroups: ["machineconfiguration.openshift.io"]
  resources:
  - machineconfigs
  - machineconfigpools
  - controllerconfigs
  - kubeletconfigs
  - machineosbuilds
  - machineosconfigs
  - machineconfignodes
  - pinnedimagesets
  verbs:
  - get
  - list
- apiGroups: ["tuned.openshift.io"]
  resources:
  - tuneds
  verbs:
  - get
  - list
- apiGroups: ["performance.openshift.io"]
  resources:
  - performanceprofiles
  verbs:
  - get
  - list
- apiGroups: ["node.k8s.io"]
  resources:
  - runtimeclasses
  verbs:
  - get
  - list
- apiGroups: ["operators.coreos.com"]
  resources:
  - subscriptions
  - clusterserviceversions
  - catalogsources
  - installplans
  - operatorgroups
  verbs:
  - get
  - list
- apiGroups: ["apiserver.openshift.io"]
  resources:
  - apirequestcounts
  verbs:
  - get
  - list
- apiGroups: ["k8s.ovn.org"]
  resources:
  - egressips
  - adminnetworkpolicies
  - baselineadminnetworkpolicies
  - routeadvertisements
  verbs:
  - get
  - list
- apiGroups: ["network.openshift.io"]
  resources:
  - hostsubnets
  - netnamespaces
  - egressnetworkpolicies
  verbs:
  - get
  - list
- apiGroups: ["cloud.network.openshift.io"]
  resources:
  - cloudprivateipconfigs
  verbs:
  - get
  - list
- apiGroups: ["networking.k8s.io"]
  resources:
  - networkpolicies
  verbs:
  - get
  - list
- apiGroups: ["policy.networking.k8s.io"]
  resources:
  - adminnetworkpolicies
  - baselineadminnetworkpolicies
  verbs:
  - get
  - list
- apiGroups: ["k8s.cni.cncf.io"]
  resources:
  - network-attachment-definitions
  - multi-networkpolicies
  verbs:
  - get
  - list
- apiGroups: ["whereabouts.cni.cncf.io"]
  resources:
  - ippools
  - overlappingrangeipreservations
  verbs:
  - get
  - list
- apiGroups: ["nmstate.io"]
  resources:
  - nmstates
  - nodenetworkstates
  - nodenetworkconfigurationenactments
  - nodenetworkconfigurationpolicies
  verbs:
  - get
  - list
- apiGroups: ["sriovnetwork.openshift.io"]
  resources:
  - sriovnetworknodepolicies
  - sriovnetworknodestates
  - sriovnetworkpoolconfigs
  - sriovnetworks
  - sriovoperatorconfigs
  - sriovibnetworks
  verbs:
  - get
  - list
- apiGroups: ["metallb.io"]
  resources:
  - bgppeers
  - bfdprofiles
  - bgpadvertisements
  - ipaddresspools
  - l2advertisements
  - communities
  - metallbs
  verbs:
  - get
  - list
- apiGroups: ["frrk8s.metallb.io"]
  resources:
  - frrconfigurations
  verbs:
  - get
  - list
- apiGroups: ["cns.vmware.com"]
  resources:
  - csinodetopologies
  - cnsvspherevolumemigrations
  - cnsvolumeoperationrequests
  verbs:
  - get
  - list
- apiGroups: ["aro.openshift.io"]
  resources:
  - clusters
  verbs:
  - get
  - list
- apiGroups: ["operator.openshift.io"]
  resources:
  - clustercsidrivers
  verbs:
  - get
  - list
- apiGroups: ["updateservice.operator.openshift.io"]
  resources:
  - updateservices
  verbs:
  - get
  - list
- apiGroups: ["controlplane.operator.openshift.io"]
  resources:
  - podnetworkconnectivitychecks
  verbs:
  - get
  - list
- apiGroups: ["k8s.ovn.org"]
  resources:
  - egressfirewalls
  verbs:
  - get
  - list
- apiGroups: ["ingressnodefirewall.openshift.io"]
  resources:
  - ingressnodefirewalls
  verbs:
  - get
  - list
- apiGroups: ["apps"]
  resources:
  - deployments
  verbs:
  - get  # To find insights operator deployment
- apiGroups: ["apps"]
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - create  # For temporary perf-node-gather-daemonset
  - delete  # For cleanup of temporary daemonset
# Raw API Access for specific endpoints
# Note: These require special handling and should be restricted in production
- nonResourceURLs:
  - "/debug/api_priority_and_fairness/*"  # API Priority and Fairness debugging
  - "/metrics"  # Metrics endpoint
  verbs:
  - get
- apiGroups: ["monitoring.coreos.com"]
  resources:
  - prometheuses
  - alertmanagers
  - servicemonitors
  verbs:
  - get
  - list
- apiGroups: ["machine.openshift.io"]
  resources:
  - machines
  - machinesets
  verbs:
  - get
  - list
- apiGroups: ["user.openshift.io"]
  resources:
  - users
  - groups
  verbs:
  - get
  - list
- apiGroups: ["security.openshift.io"]
  resources:
  - securitycontextconstraints
  verbs:
  - get
  - list
- apiGroups: ["route.openshift.io"]
  resources:
  - routes
  verbs:
  - get
  - list
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  resourceNames:
  - cluster-monitoring-config
  - alertmanager-main
  verbs:
  - get
  namespaces:
  - openshift-monitoring
  - openshift-user-workload-monitoring
- apiGroups: ["*"]
  resources:
  - "*/status"
  - "*/scale"
  verbs:
  - get
- apiGroups: [""]
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups: ["image.openshift.io"]
  resources:
  - images
  - imagestreamtags
  - imagestreams
  verbs:
  - get
  - list
- apiGroups: ["build.openshift.io"]
  resources:
  - builds
  - buildconfigs
  verbs:
  - get
  - list
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  - statefulsets
  - daemonsets
  verbs:
  - get
  - list
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
- apiGroups: ["policy"]
  resources:
  - poddisruptionbudgets
  - podsecuritypolicies
  verbs:
  - get
  - list
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
- apiGroups: ["authorization.openshift.io"]
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
