// Code generated by go-bindata. (@generated) DO NOT EDIT.

//Package testdata generated by go-bindata.// sources:
// test/e2e/extension/testdata/OWNERS
// test/e2e/extension/testdata/fixtures.go
// test/e2e/extension/testdata/mustgather/mustgather-audit.yaml
// test/e2e/extension/testdata/mustgather/mustgather-noupload.yaml
// test/e2e/extension/testdata/mustgather/mustgather-proxy.yaml
// test/e2e/extension/testdata/mustgather/mustgather-pvc.yaml
// test/e2e/extension/testdata/mustgather/mustgather-retain.yaml
// test/e2e/extension/testdata/mustgather/mustgather-timeout.yaml
// test/e2e/extension/testdata/mustgather/mustgather-upload.yaml
// test/e2e/extension/testdata/mustgather/mustgather.yaml
// test/e2e/extension/testdata/mustgather/namespace.yaml
// test/e2e/extension/testdata/mustgather/operatorgroup.yaml
// test/e2e/extension/testdata/mustgather/pvc.yaml
// test/e2e/extension/testdata/mustgather/reader-pod.yaml
// test/e2e/extension/testdata/mustgather/subscription.yaml
package testdata

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// ModTime return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _owners = []byte(`approvers:
  - KeenonLee
  - lunarwhite
  - emmajiafan
`)

func ownersBytes() ([]byte, error) {
	return _owners, nil
}

func owners() (*asset, error) {
	bytes, err := ownersBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "OWNERS", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _fixturesGo = []byte(`package testdata

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

var (
	fixtureDir string
)

func init() {
	var err error
	fixtureDir, err = ioutil.TempDir("", "testdata-fixtures-")
	if err != nil {
		panic(fmt.Sprintf("failed to create fixture directory: %v", err))
	}
}

func FixturePath(elem ...string) string {
	relativePath := filepath.Join(elem...)
	targetPath := filepath.Join(fixtureDir, relativePath)

	if _, err := os.Stat(targetPath); err == nil {
		return targetPath
	}

	if err := os.MkdirAll(filepath.Dir(targetPath), 0755); err != nil {
		panic(fmt.Sprintf("failed to create directory for %s: %v", relativePath, err))
	}

	bindataPath := relativePath
	tempDir, err := os.MkdirTemp("", "bindata-extract-")
	if err != nil {
		panic(fmt.Sprintf("failed to create temp directory: %v", err))
	}
	defer os.RemoveAll(tempDir)

	if err := RestoreAsset(tempDir, bindataPath); err != nil {
		if err := RestoreAssets(tempDir, bindataPath); err != nil {
			panic(fmt.Sprintf("failed to restore fixture %s: %v", relativePath, err))
		}
	}

	extractedPath := filepath.Join(tempDir, bindataPath)
	if err := os.Rename(extractedPath, targetPath); err != nil {
		panic(fmt.Sprintf("failed to move extracted files: %v", err))
	}

	return targetPath
}

func CleanupFixtures() error {
	if fixtureDir != "" {
		return os.RemoveAll(fixtureDir)
	}
	return nil
}

func GetFixtureData(elem ...string) ([]byte, error) {
	relativePath := filepath.Join(elem...)
	cleanPath := relativePath
	if len(cleanPath) > 0 && cleanPath[0] == '/' {
		cleanPath = cleanPath[1:]
	}
	return Asset(cleanPath)
}

func MustGetFixtureData(elem ...string) []byte {
	data, err := GetFixtureData(elem...)
	if err != nil {
		panic(fmt.Sprintf("failed to get fixture data: %v", err))
	}
	return data
}

func FixtureExists(elem ...string) bool {
	relativePath := filepath.Join(elem...)
	cleanPath := relativePath
	if len(cleanPath) > 0 && cleanPath[0] == '/' {
		cleanPath = cleanPath[1:]
	}
	_, err := Asset(cleanPath)
	return err == nil
}

func ListFixtures() []string {
	names := AssetNames()
	fixtures := make([]string, 0, len(names))
	for _, name := range names {
		if strings.HasPrefix(name, "testdata/") {
			fixtures = append(fixtures, strings.TrimPrefix(name, "testdata/"))
		}
	}
	sort.Strings(fixtures)
	return fixtures
}
`)

func fixturesGoBytes() ([]byte, error) {
	return _fixturesGo, nil
}

func fixturesGo() (*asset, error) {
	bytes, err := fixturesGoBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "fixtures.go", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _mustgatherMustgatherAuditYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mustgather-audit-template
objects:
  - apiVersion: operator.openshift.io/v1alpha1
    kind: MustGather
    metadata:
      name: "${NAME}"
      namespace: "${NAMESPACE}"
    spec:
      serviceAccountName: "${SA}"
      retainResourcesOnCompletion: ${{RETAIN_RESOURCES}}
      audit: ${{AUDIT}}
      storage:
        type: PersistentVolume
        persistentVolume:
          claim:
            name: "${PVCNAME}"
          subPath: "${SUBPATH}"
parameters:
  - name: NAME
  - name: NAMESPACE
  - name: SA
    value: "must-gather-operator"
  - name: RETAIN_RESOURCES
  - name: AUDIT
    value: "false"
  - name: PVCNAME
  - name: SUBPATH
    value: "must-gather-bundles/case-04230315"
`)

func mustgatherMustgatherAuditYamlBytes() ([]byte, error) {
	return _mustgatherMustgatherAuditYaml, nil
}

func mustgatherMustgatherAuditYaml() (*asset, error) {
	bytes, err := mustgatherMustgatherAuditYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "mustgather/mustgather-audit.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _mustgatherMustgatherNouploadYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mustgather-noupload-template
objects:
  - apiVersion: operator.openshift.io/v1alpha1
    kind: MustGather
    metadata:
      name: "${NAME}"
      namespace: "${NAMESPACE}"
    spec:
      serviceAccountName: "${SA}"
      retainResourcesOnCompletion: ${{RETAIN_RESOURCES}}
parameters:
  - name: NAME
  - name: NAMESPACE
  - name: SA
    value: "must-gather-operator"
  - name: RETAIN_RESOURCES
    value: "true"
`)

func mustgatherMustgatherNouploadYamlBytes() ([]byte, error) {
	return _mustgatherMustgatherNouploadYaml, nil
}

func mustgatherMustgatherNouploadYaml() (*asset, error) {
	bytes, err := mustgatherMustgatherNouploadYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "mustgather/mustgather-noupload.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _mustgatherMustgatherProxyYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mustgather-proxy-template
objects:
  - apiVersion: operator.openshift.io/v1alpha1
    kind: MustGather
    metadata:
      name: "${NAME}"
      namespace: "${NAMESPACE}"
    spec:
      serviceAccountName: "${SA}"
      proxyConfig:
        httpProxy: "${HTTP_PROXY}"
        httpsProxy: "${HTTPS_PROXY}"
        noProxy: "${NO_PROXY}"
      uploadTarget:
        type: SFTP
        sftp:
          caseID: "${CASEID}"
          caseManagementAccountSecretRef:
            name: "${CASESECRET}"
parameters:
  - name: NAME
  - name: NAMESPACE
  - name: CASEID
    value: "04230315"
  - name: CASESECRET
    value: "mustgather-creds"
  - name: SA
    value: "must-gather-operator"
  - name: HTTP_PROXY
  - name: HTTPS_PROXY
  - name: NO_PROXY
`)

func mustgatherMustgatherProxyYamlBytes() ([]byte, error) {
	return _mustgatherMustgatherProxyYaml, nil
}

func mustgatherMustgatherProxyYaml() (*asset, error) {
	bytes, err := mustgatherMustgatherProxyYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "mustgather/mustgather-proxy.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _mustgatherMustgatherPvcYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mustgather-pvc-template
objects:
  - apiVersion: operator.openshift.io/v1alpha1
    kind: MustGather
    metadata:
      name: "${NAME}"
      namespace: "${NAMESPACE}"
    spec:
      serviceAccountName: "${SA}"
      retainResourcesOnCompletion: true
      uploadTarget:
        type: SFTP
        sftp:
          caseID: "${CASEID}"
          caseManagementAccountSecretRef:
            name: "${CASESECRET}"
          internalUser: true
      storage:
        type: PersistentVolume
        persistentVolume:
          claim:
            name: "${PVCNAME}"
          subPath: "${SUBPATH}"
parameters:
  - name: NAME
  - name: NAMESPACE
  - name: SA
    value: "must-gather-operator"
  - name: CASEID
    value: "04230315"
  - name: CASESECRET
  - name: PVCNAME
  - name: SUBPATH
    value: "must-gather-bundles/case-04230315"
`)

func mustgatherMustgatherPvcYamlBytes() ([]byte, error) {
	return _mustgatherMustgatherPvcYaml, nil
}

func mustgatherMustgatherPvcYaml() (*asset, error) {
	bytes, err := mustgatherMustgatherPvcYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "mustgather/mustgather-pvc.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _mustgatherMustgatherRetainYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mustgather-retain-template
objects:
  - apiVersion: operator.openshift.io/v1alpha1
    kind: MustGather
    metadata:
      name: "${NAME}"
      namespace: "${NAMESPACE}"
    spec:
      serviceAccountName: "${SA}"
      retainResourcesOnCompletion: ${{RETAIN_RESOURCES}}
      uploadTarget:
        type: SFTP
        sftp:
          caseID: "${CASEID}"
          caseManagementAccountSecretRef:
            name: "${CASESECRET}"
          internalUser: true
parameters:
  - name: NAME
  - name: NAMESPACE
  - name: CASEID
    value: "04230315"
  - name: CASESECRET
    value: "mustgather-creds"
  - name: SA
    value: "must-gather-operator"
  - name: RETAIN_RESOURCES
    value: "false"
`)

func mustgatherMustgatherRetainYamlBytes() ([]byte, error) {
	return _mustgatherMustgatherRetainYaml, nil
}

func mustgatherMustgatherRetainYaml() (*asset, error) {
	bytes, err := mustgatherMustgatherRetainYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "mustgather/mustgather-retain.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _mustgatherMustgatherTimeoutYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mustgather-timeout-template
objects:
  - apiVersion: operator.openshift.io/v1alpha1
    kind: MustGather
    metadata:
      name: "${NAME}"
      namespace: "${NAMESPACE}"
    spec:
      serviceAccountName: "${SA}"
      mustGatherTimeout: "${TIMEOUT}"
parameters:
  - name: NAME
  - name: NAMESPACE
  - name: TIMEOUT
    value: "10s"
  - name: SA
    value: "must-gather-operator"
`)

func mustgatherMustgatherTimeoutYamlBytes() ([]byte, error) {
	return _mustgatherMustgatherTimeoutYaml, nil
}

func mustgatherMustgatherTimeoutYaml() (*asset, error) {
	bytes, err := mustgatherMustgatherTimeoutYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "mustgather/mustgather-timeout.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _mustgatherMustgatherUploadYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mustgather-template
objects:
  - apiVersion: operator.openshift.io/v1alpha1
    kind: MustGather
    metadata:
      name: "${NAME}"
      namespace: "${NAMESPACE}"
    spec:
      serviceAccountName: "${SA}"
      uploadTarget:
        type: SFTP
        sftp:
          caseID: "${CASEID}"
          caseManagementAccountSecretRef:
            name: "${CASESECRET}"
parameters:
  - name: NAME
  - name: NAMESPACE
  - name: CASEID
    value: "04230315"
  - name: CASESECRET
    value: "mustgather-creds"
  - name: SA
    value: "must-gather-operator"

`)

func mustgatherMustgatherUploadYamlBytes() ([]byte, error) {
	return _mustgatherMustgatherUploadYaml, nil
}

func mustgatherMustgatherUploadYaml() (*asset, error) {
	bytes, err := mustgatherMustgatherUploadYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "mustgather/mustgather-upload.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _mustgatherMustgatherYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mustgather-template
objects:
  - apiVersion: operator.openshift.io/v1alpha1
    kind: MustGather
    metadata:
      name: "${NAME}"
      namespace: "${NAMESPACE}"
    spec:
      serviceAccountName: "${SA}"
      uploadTarget:
        type: SFTP
        sftp:
          caseID: "${CASEID}"
          caseManagementAccountSecretRef:
            name: "${CASESECRET}"
parameters:
  - name: NAME
  - name: NAMESPACE
  - name: CASEID
    value: "04230315"
  - name: CASESECRET
    value: "mustgather-creds"
  - name: SA
    value: "must-gather-operator"

`)

func mustgatherMustgatherYamlBytes() ([]byte, error) {
	return _mustgatherMustgatherYaml, nil
}

func mustgatherMustgatherYaml() (*asset, error) {
	bytes, err := mustgatherMustgatherYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "mustgather/mustgather.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _mustgatherNamespaceYaml = []byte(`apiVersion: v1
kind: Namespace
metadata:
  name: must-gather-operator
`)

func mustgatherNamespaceYamlBytes() ([]byte, error) {
	return _mustgatherNamespaceYaml, nil
}

func mustgatherNamespaceYaml() (*asset, error) {
	bytes, err := mustgatherNamespaceYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "mustgather/namespace.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _mustgatherOperatorgroupYaml = []byte(`apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: must-gather-og
  namespace: must-gather-operator
`)

func mustgatherOperatorgroupYamlBytes() ([]byte, error) {
	return _mustgatherOperatorgroupYaml, nil
}

func mustgatherOperatorgroupYaml() (*asset, error) {
	bytes, err := mustgatherOperatorgroupYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "mustgather/operatorgroup.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _mustgatherPvcYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mustgather-pvc-template
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: "${NAME}"
      namespace: "${NAMESPACE}"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "${STORAGE}"
parameters:
  - name: NAME
  - name: NAMESPACE
  - name: STORAGE
    value: "5Gi"
`)

func mustgatherPvcYamlBytes() ([]byte, error) {
	return _mustgatherPvcYaml, nil
}

func mustgatherPvcYaml() (*asset, error) {
	bytes, err := mustgatherPvcYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "mustgather/pvc.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _mustgatherReaderPodYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mustgather-reader-pod-template
objects:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: "${NAME}"
      namespace: "${NAMESPACE}"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: reader-container
        image: registry.access.redhat.com/ubi9/ubi-minimal:latest
        command: ["sleep", "3600"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: "${PVCNAME}"
      restartPolicy: Never
parameters:
  - name: NAME
  - name: NAMESPACE
  - name: PVCNAME
`)

func mustgatherReaderPodYamlBytes() ([]byte, error) {
	return _mustgatherReaderPodYaml, nil
}

func mustgatherReaderPodYaml() (*asset, error) {
	bytes, err := mustgatherReaderPodYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "mustgather/reader-pod.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _mustgatherSubscriptionYaml = []byte(`apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: subscription-template
objects:
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: "${NAME}"
    spec:
      channel: "${CHANNEL}"
      installPlanApproval: Automatic
      name: "${NAME}"
      source: "${SOURCE}"
      sourceNamespace: "${SOURCE_NAMESPACE}"
parameters:
  - name: NAME
  - name: SOURCE
  - name: SOURCE_NAMESPACE
  - name: CHANNEL
`)

func mustgatherSubscriptionYamlBytes() ([]byte, error) {
	return _mustgatherSubscriptionYaml, nil
}

func mustgatherSubscriptionYaml() (*asset, error) {
	bytes, err := mustgatherSubscriptionYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "mustgather/subscription.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"OWNERS":                              owners,
	"fixtures.go":                         fixturesGo,
	"mustgather/mustgather-audit.yaml":    mustgatherMustgatherAuditYaml,
	"mustgather/mustgather-noupload.yaml": mustgatherMustgatherNouploadYaml,
	"mustgather/mustgather-proxy.yaml":    mustgatherMustgatherProxyYaml,
	"mustgather/mustgather-pvc.yaml":      mustgatherMustgatherPvcYaml,
	"mustgather/mustgather-retain.yaml":   mustgatherMustgatherRetainYaml,
	"mustgather/mustgather-timeout.yaml":  mustgatherMustgatherTimeoutYaml,
	"mustgather/mustgather-upload.yaml":   mustgatherMustgatherUploadYaml,
	"mustgather/mustgather.yaml":          mustgatherMustgatherYaml,
	"mustgather/namespace.yaml":           mustgatherNamespaceYaml,
	"mustgather/operatorgroup.yaml":       mustgatherOperatorgroupYaml,
	"mustgather/pvc.yaml":                 mustgatherPvcYaml,
	"mustgather/reader-pod.yaml":          mustgatherReaderPodYaml,
	"mustgather/subscription.yaml":        mustgatherSubscriptionYaml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"OWNERS":      {owners, map[string]*bintree{}},
	"fixtures.go": {fixturesGo, map[string]*bintree{}},
	"mustgather": {nil, map[string]*bintree{
		"mustgather-audit.yaml":    {mustgatherMustgatherAuditYaml, map[string]*bintree{}},
		"mustgather-noupload.yaml": {mustgatherMustgatherNouploadYaml, map[string]*bintree{}},
		"mustgather-proxy.yaml":    {mustgatherMustgatherProxyYaml, map[string]*bintree{}},
		"mustgather-pvc.yaml":      {mustgatherMustgatherPvcYaml, map[string]*bintree{}},
		"mustgather-retain.yaml":   {mustgatherMustgatherRetainYaml, map[string]*bintree{}},
		"mustgather-timeout.yaml":  {mustgatherMustgatherTimeoutYaml, map[string]*bintree{}},
		"mustgather-upload.yaml":   {mustgatherMustgatherUploadYaml, map[string]*bintree{}},
		"mustgather.yaml":          {mustgatherMustgatherYaml, map[string]*bintree{}},
		"namespace.yaml":           {mustgatherNamespaceYaml, map[string]*bintree{}},
		"operatorgroup.yaml":       {mustgatherOperatorgroupYaml, map[string]*bintree{}},
		"pvc.yaml":                 {mustgatherPvcYaml, map[string]*bintree{}},
		"reader-pod.yaml":          {mustgatherReaderPodYaml, map[string]*bintree{}},
		"subscription.yaml":        {mustgatherSubscriptionYaml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
